# sudo-enabled Ubuntu Trusty
dist: trusty

# running each build in isolated GCE VM
sudo: false

language: python
python: "2.7"

env:
  global:
    - DIR_BIN=/travis/bin
    - DIR_TMP=/travis/tmp
    - PACKER_VERSION=1.1.3
    - TERRAFORM_VERSION=0.11.2
    - TERRAFORM_LINT_VERSION=0.5.4
  matrix:
    - USE_ENV=stage
    - USE_ENV=prod

# https://docs.travis-ci.com/user/installing-dependencies/
before_install:
  #- sudo apt-get -qq update
  - sudo apt install -y wget

install:

  # making dirs
  - sudo mkdir -p ${DIR_BIN} ${DIR_TMP}
  - sudo chmod 777 ${DIR_BIN} ${DIR_TMP}

  # getting packer
  - wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip -P ${DIR_TMP}
  - unzip ${DIR_TMP}/packer_${PACKER_VERSION}_linux_amd64.zip -d ${DIR_BIN}
  - ${DIR_BIN}/packer --version

  # getting ansible
  - sudo pip install -r ansible/requirements.txt

  # getting terraform
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -P ${DIR_TMP}
  - unzip ${DIR_TMP}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d ${DIR_BIN}
  - ${DIR_BIN}/terraform --version

  # getting terraform lint
  - wget https://github.com/wata727/tflint/releases/download/v${TERRAFORM_LINT_VERSION}/tflint_darwin_amd64.zip -P ${DIR_TMP}
  - unzip ${DIR_TMP}/tflint_darwin_amd64.zip -d ${DIR_BIN}

script:

  - WORK_DIR="$(pwd)"

  # validating packer
  - cd packer
  - ${DIR_BIN}/packer validate -var-file=variables.json.example reddit-app.json
  - ${DIR_BIN}/packer validate -var-file=variables.json.example reddit-db.json
  - cd ${WORK_DIR}

  # terraform validate
  - rm ${WORK_DIR}/terraform/${USE_ENV}/backend.tf
  - cd terraform/${USE_ENV}
  - mkdir .ssh && cd .ssh
  - touch appuser.pub appuser appuser1.pub appuser2.pub
  - cd ..
  - ${DIR_BIN}/terraform init
  - ${DIR_BIN}/terraform validate --var-file=${WORK_DIR}/terraform/code/terraform.tfvars.example
  - cd ${WORK_DIR}



