---
- name: Configure App
  hosts:
    - app
    - reddit-app*
  become: true
  vars:
    mongo_port: 27017
    db_host: 10.132.0.5
    app_port: 9292

  tasks:
    - name: Add unit to puma
      template:
        src: templates/puma.service.j2
        dest: /etc/systemd/system/puma.service
      notify:
        - restart puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser
      notify:
        - restart puma

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: systemd reload
      systemd: daemon_reload=yes

    - name: restart puma
      systemd: name=puma daemon_reload=yes state=restarted

    - name: reload puma
      systemd: name=puma state=reloaded
