---
- name: Install bundle
  hosts: app
  tags: deploy-tag

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      notify: reload puma

  handlers:
    - name: reload puma
      become: true
      systemd: name=puma state=reloaded
