---
  
- name: Configure hosts & deploy applications
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    mongo_port: 27017
    db_host: 10.132.0.5
    app_port: 9293

  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/Otus-DevOps-2017-11/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      tags: deploy-tag
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag
      notify: restart puma

    - name: Add unit to puma
      become: true
      template:
        src: templates/puma.service.j2
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify:
        - systemd reload
        - restart puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
      tags: app-tag
      notify:
        - restart puma

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

  handlers:
    - name: restart mongod
      become: true
      service: name=mongod state=restarted

    - name: systemd reload
      become: true
      systemd: daemon_reload=yes

    - name: reload puma
      become: true
      systemd: name=puma state=reloaded

    - name: restart puma
      become: true
      systemd: name=puma state=restarted

